spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/sys-resource
    username: postgres
    password: postgres

server:
  port: 19050
  servlet:
    context-path: /resource

info:
  cluster:
    id: 10
    level: 1
    name: default



