server:
  port: ${server_port:19030}
  servlet:
    context-path: /code

info:
  cluster:
    id: ${cluster_id:10}
    level: ${cluster_level:1}
    name: ${cluster_name:default}

spring:
  datasource:
    url: ${datasource_url:jdbc:postgresql://127.0.0.1:5432/sys-code}
    username: ${datasource_username:postgres}
    password: ${datasource_password:postgres}
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos_server:10.64.4.74:8848}
