info:
  application:
    name: ${spring.application.name}
    version: 0.0.0
    build: 2022-11-09 14:32:33
  commit:
    version: master xxxx
    Author: xxx
    Time: 1970-01-01 00:00:00
    Msg: create
  maintainer:
    "[shanhuiming@cowave.com]": 单惠铭

spring:
  application:
    name: sys-code
  messages:
    basename: META-INF/i18n/messages,META-INF/i18n/messages-frame
  jackson:
    time-zone: GMT+8
  liquibase:
    enabled: true
    change-log: sql/changelog.yml
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false
    nacos:
      discovery:
        metadata:
          path: ${server.servlet.context-path}
          management:
            context-path: ${server.servlet.context-path}/actuator

mybatis-plus:
  global-config:
    banner: false

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
  health:
    mail:
      enabled: false
    ping:
      enabled: false
    diskSpace:
      enabled: false
