server:
  port: ${http_port:19030}
  servlet:
    context-path: /meter

spring:
  access:
    filter:
      - /api/v1/*
    auth:
      enable: true
      mode: access-refresh
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/sys-meter
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: sql/changelog.yml
