global:
  resolve_timeout: 10m             ## 多久时间没有报警则声明为已解决

route:
  group_by: ["cluster"]
  group_wait: 60s                 ## 分组创建后初始化等待时长
  group_interval: 60s             ## 告警发送之前的等待时长
  repeat_interval: 30m            ## 重复告警的间隔时长
  receiver: 'default'
  routes:
  - receiver: 'log-sys'
    match:
      job: log-sys
    continue: false
  - receiver: 'sys'
    match:
      cluster: sys管理

receivers:
- name: 'default'
- name: 'sys'
  webhook_configs:
  - url: http://10.64.4.74:8060/dingtalk/sys/send
    send_resolved: false
- name: 'log-sys'
  webhook_configs:
  - url: http://10.64.4.74:8060/dingtalk/log-sys/send
    send_resolved: false
