version: '3'

services:
  sys-eureka:
    image: cowave.com/sys-eureka:1.0.0
    container_name: sys-eureka
    network_mode: host
    ports:
      - 11001:11001
    volumes:
      - ./sys-eureka:/opt/cowave/sys-eureka/log
    environment:
      TZ: Asia/Shanghai
      jvm_option: -Xms256m -Xmx256m -XX:MetaspaceSize=128m -XX:+HeapDumpOnOutOfMemoryError
      server_port: 11001
      server_name: sys-eureka
      eureka_instance_id: 10.64.4.74:11001
      mail_enable: "false"
      mail_addr: shanhm1991@163.com
      dingtalk_enable: "false"
      dingtalk_hook:
      dingtalk_secret:
