apiVersion: apps/v1
kind: Deployment
metadata:
  name: sys-eureka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sys-eureka
  template:
    metadata:
      labels:
        app: sys-eureka
    spec:
      containers:
        - name: sys-eureka
          image: cowave.com/sys-eureka:1.0.0
          ports:
            - containerPort: 11001
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: JVM_OPTION
              value: "-Xms256m -Xmx256m -XX:MetaspaceSize=128m -XX:+HeapDumpOnOutOfMemoryError"
            - name: SERVER_PORT
              value: "11001"
            - name: SERVER_NAME
              value: "sys-eureka"
            - name: EUREKA_INSTANCE_ID
              value: "192.168.141.74:11001"
            - name: MAIL_ENABLE
              value: "false"
            - name: MAIL_ADDR
              value: shanhm1991@163.com
            - name: DINGTALK_ENABLE
              value: "false"
          volumeMounts:
            - mountPath: /opt/cowave/sys-eureka/log
              name: sys-eureka-log-volume
      volumes:
        - name: sys-eureka-log-volume
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: sys-eureka-nodeport
spec:
  type: NodePort
  selector:
    app: sys-eureka
  ports:
    - name: http
      port: 11001
      targetPort: 11001
      nodePort: 31001

---
apiVersion: v1
kind: Service
metadata:
  name: sys-eureka-clusterip
spec:
  selector:
    app: sys-eureka
  ports:
    - port: 11001
      targetPort: 11001
  type: ClusterIP
