server:
  port: ${http_port:19040}
  servlet:
    context-path: /job

spring:
  application:
    name: sys-job
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/sys-job
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: sql/changelog.yml
  job:
    server:
      address: localhost:19040
