app:
  id: sys-resource

apollo:
  meta: http://127.0.0.1:19001
  cluster: default
  cache-dir: ./apollo
  bootstrap:
    enabled: false
    namespaces: application,common
    eagerLoad:
      enabled: true
