info:
  application:
    name: ${spring.application.name}
    version: 0.0.0
    build: 2022-11-09 14:32:33
  commit:
    version: master xxxx
    Author: xxx
    Time: 1970-01-01 00:00:00
    Msg: create
  maintainer:
    "[shanhuiming@cowave.com]": 单惠铭

spring:
  application:
    name: sys-resource
  jackson:
    time-zone: GMT+8
  liquibase:
    enabled: true
    change-log: sql/changelog.yml
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false
  datasource:
    druid:
      initialSize: 5
      minIdle: 10
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      maxEvictableIdleTimeMillis: 900000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        allow:
        url-pattern: /druid/*
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 5000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

mybatis-plus:
  global-config:
    banner: false

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
  health:
    ping:
      enabled: false
    diskSpace:
      enabled: false
