server:
  port: 19040
  servlet:
    context-path: /quartz

info:
  cluster:
    id: 10
    level: 1
    name: default

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://10.64.4.74:5432/sys-quartz
    username: postgres
    password: postgres
  cloud:
    nacos:
      discovery:
        server-addr: 10.64.4.74:8848
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceName: localhost
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            tablePrefix: qrtz_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
