spring:
  access:
    always-success: true
    filter:
      - /api/v1/*
    auth:
      enable: true
      mode: access-refresh
      accessExpire: 60
      ignoreUrls:
        - /api/v1/oauth/client/redirect/**
        - /api/v1/oauth/client/authorize/token
        - /api/v1/auth/public/**
        - /api/v1/flow/designer/**
        - /designer/**
        - /favicon.ico
        - /actuator/**
        - /doc/**
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/sys-admin
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: sql/changelog.yml
  redis:
    host: 127.0.0.1
    port: 6379
  elasticsearch:
    rest:
      uris: 127.0.0.1:9200
  minio:
    endpoint: http://10.64.4.74:39000
    accessKey: admin
    secretKey: admin123
  socket-io:
    port: 19011
  mail:
    host: smtp.163.com
    username: cowaveAdmin@163.com
    password: TQQWRIRSQLTEELPT

flowable:
  database-schema-update: true
