spring:
  access:
    filter:
      - /api/v1/*
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/sys-meter
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: sql/changelog.yml
